services:
  app:
    image: ghcr.io/tamfrost/hfbcast:latest
    container_name: hfbcast-app
    build:
      context: .
      args:
        COMMIT_SHA: compose
        APP_VERSION: "1.2.3"
    ports:
      - 58080:8080

