services:
  app:
    image: ghcr.io/tamfrost/hfbcast:latest
    container_name: hfbcast-app
    build:
      context: .
      args:
        COMMIT_SHA: ${COMMIT_SHA}
        APP_VERSION: ${APP_VERSION}
    ports:
      - 58080:8080

